### ISSUE TITLE
Other pictures

### ISSUE THREAD

**Issue by mollykc** [maxtkc/mos-herb-site#10]
I'd love to have other pictures in other pages, on the sides of / along with the text. The one of me reaching up and harvesting (currently the work with me banner) would be great in the work with me page, smaller and on the side. The one of me and Dianne laughing at each other would be great for the about me page (with image description at the bottom: "Mo (right) and a colleague, making medicine". The home page could include the anise hyssop picture (purple spike flower with orange ones in background).

**Comment by maxtkc** [comment]
added images, couldn't get the caption. I can figure it out if you really want it, but make it a separate issue
