### ISSUE TITLE
Add to bottom of home page:

### ISSUE THREAD

**Issue by mollykc** [maxtkc/mos-herb-site#14]
When I first considered seeing Mo, I thought: "do I really need an herbalist?” I know now what a silly question it was! If you eat food, you need an herbalist! Mo has thoughtfully explained how herbs can support me, and has empowered me to be an active participant in my general healthcare, and to learn more about plants and our relationship to nature. Immune support with young kids has been so important, and support through winter during breastfeeding has helped me immensely in knowing I’m doing the right thing for my body and infant. Mo has recommended several books on herbs and growing my own herbs. I feel so supported! Mo meets you where you are, with no judgement, only kind consideration. If you’re on the fence, do it!

**Comment by mollykc** [comment]
Or maybe on the side of the page, if it could look nice? Ideally in italics?

**Comment by maxtkc** [comment]
I think bottom is good. I am not an expert in design but it's good to have empty space so we should probably leave the margins as is if we can. It also makes it very easy to be mobile friendly. If we move something into the margins, we should have a good reason for doing it.
