### ISSUE TITLE
Add to side of work with me page:

### ISSUE THREAD

**Issue by mollykc** [maxtkc/mos-herb-site#15]
The face compress you gave me is truly magical! I've been experimenting with different products and realized everything except the compress causes me to break out. The compress both works for my dry patches and my breakout areas -- thank you so much!

**Comment by maxtkc** [comment]
at first I thought that your description was meant as a snide comment about how I had put one of your images on the website and that I had squished it or something

**Comment by mollykc** [comment]
oh lol.

also, prob obvious but should be either italics or in quotes
