### ISSUE TITLE
Banner text

### ISSUE THREAD

**Issue by mollykc** [maxtkc/mos-herb-site#2]
Replace "Mo's Herbs" with: Mo Katz-Christy, Clinical Herbalist

make text legible

**Comment by maxtkc** [comment]
still need to *make text legible* but waiting to do banner pictures first.

**Comment by maxtkc** [comment]
darkened images slightly and made text white. We can also do lighten image and black text, but I think the white text looks better.

**Comment by mollykc** [comment]
Love it!!
