### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by mollykc** [maxtkc/mos-herb-site#6]
Change to:

Email address:
Name:
Message:

Make all required.

Underneath, add: "Or, email Mo at mkatzchristy (at) gmail.com."

**Comment by maxtkc** [comment]
we need to make a google form for this page to actually work

**Comment by mollykc** [comment]
Underneath, add: "Or, email Mo at mkatzchristy (at) gmail.com."

**Comment by mollykc** [comment]
ooh, what a snazzy form!
